"""add status to ClickEntry

Revision ID: 6a974c62f346
Revises: 
Create Date: 2025-05-16 20:24:42.448712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a974c62f346'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_keywords')
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.drop_index('keyword')

    op.drop_table('keyword')
    with op.batch_alter_table('click_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.alter_column('keyword',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('keywords',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('keywords',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('click_entry', schema=None) as batch_op:
        batch_op.alter_column('keyword',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('status')

    op.create_table('keyword',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('keyword', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.create_index('keyword', ['keyword'], unique=True)

    op.create_table('job_keywords',
    sa.Column('job_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keyword_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='job_keywords_ibfk_1'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], name='job_keywords_ibfk_2'),
    sa.PrimaryKeyConstraint('job_id', 'keyword_id')
    )
    # ### end Alembic commands ###
